### ISSUE TITLE
Can you update to the latest jimp package? It will make this library work in CF workers.

### ISSUE THREAD

**Issue by CMCDragonkai** [oslllo/potrace#61]
The CF workers has a special environment, the latest jimp dependency makes it compatible.

All you need to do is update the package version of jimp.

**Comment by Ghustavh97** [comment]
It looks like the latest version of jimp has breaking changes. Tests are failing. I don't know when I will get time to be able to update it.

**Comment by CMCDragonkai** [comment]
We were able to to make use of it just by bumping up the version. See: https://github.com/oslllo/potrace/compare/master...CDeltakai:potrace:master.

However not sure about the tests.

**Comment by CMCDragonkai** [comment]
> const Jimp = require('jimp').default || require('jimp');

**Comment by Ghustavh97** [comment]
Nice, that actually worked. Thanks. Check out `v4.0.0` with the latest version of jimp. Thanks for the help.

**Comment by CMCDragonkai** [comment]
Nice thanks!
